homeapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

wedding/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('homeapp.urls')),
    url(r'^search/', include('searchapp.urls')),
    url(r'^wishlist/', include('userdata.urls')),

    # django allauth urls
    url(r'^accounts/', include('allauth.urls')),
]

templates/header.html
{% block header %}
    <!-- start header -->
    <header>
        <div class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'home:index' %}"><img src="{% static 'img/logo.png' %}"
                                                                               alt="logo"/></a>
                </div>
                <div class="navbar-collapse collapse ">
                    <ul class="nav navbar-nav">

                        <li class="navhover "><a href="wishlist.html" title="Wedding Checklist"><i
                                class="fa fa-heart fa-2x " style=" padding-top:4px;"><span class="badge"
                                                                                           style="background-color: #E91E63"></span></i></a>
                        </li>

                        <li class="active"><a href="{% url 'home:index' %}">Home</a></li>
                        {% if not request.user.is_authenticated %}
                            <li class="navhover"><a id="loginbtn" data-toggle="modal" href="javascript:void(0)"
                                                    onclick="openLoginModal()" style="">Log In</a></li>
                        {% else %}
                            <li class="navhover">
                                <form method="post" action="{% url 'account_logout' %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-link">Log Out</button>
                                </form>
                            </li>

                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </header>


    <div class="modal fade login" id="loginModal">
        <div class="modal-dialog login animated">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Login with</h4>
                </div>
                <div class="modal-body">
                    <div class="box">
                        <div class="content">
                            <div class="social">
                                <a id="facebook_login" class="circle facebook" href="#">
                                    <i class="fa fa-facebook fa-fw"></i>
                                </a>

                                <a id="google_login" class="circle google" href="">
                                    <i class="fa fa-google-plus fa-fw"></i>
                                </a>
                            </div>
                            <div class="division">
                                <div class="line l"></div>
                                <span>or</span>
                                <div class="line r"></div>
                            </div>
                            <div class="error"></div>
                            <div class="form loginBox">
                                <form method="POST" action="{% url 'account_login' %}"
                                      accept-charset="UTF-8">{% csrf_token %}
                                    {% if redirect_field_value %}
                                        <input type="hidden" name="{{ redirect_field_name }}"
                                               value="{{ redirect_field_value }}"/>
                                    {% endif %}
                                    <input class="form-control" autofocus="autofocus" id="id_login" maxlength="150"
                                           name="login" placeholder="Username" type="text" required="">
                                    <input class="form-control" id="id_password" name="password" placeholder="Password"
                                           type="password" required="">
                                    <a class="button secondaryAction" href="{% url 'account_reset_password' %}">Forgot
                                        Password?</a>
                                    <button class="primaryAction btn btn-default btn-login" type="submit">Sign In
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="box">
                        <div class="content registerBox" style="display:none;">
                            <div class="form">
                                <form id="snform" method="post" html="{:multipart=>true}" data-remote="true"
                                      action="/register" accept-charset="UTF-8">
                                    <input id="snemail" class="form-control" type="text" placeholder="Email"
                                           name="email">
                                    <input id="snpassword" class="form-control" type="password" placeholder="Password"
                                           name="password">
                                    <input id="password_confirmation" class="form-control" type="password"
                                           placeholder="Repeat Password" name="password_confirmation">
                                    <input class="btn btn-default btn-register" type="submit" value="Create account"
                                           name="commit" href="#" onclick=" signup();return false;">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="forgot login-footer">
                            <span>
                                 <a href="javascript: showRegisterForm();">Create an account</a>?
								<a href="javascript: forgotpass();">Forgot Password</a>?
							</span>
                    </div>
                    <div class="forgot register-footer" style="display:none">
                        <span>Already have an account?</span>
                        <a href="javascript: showLoginForm();">Login</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end header -->

{% endblock %}